### ISSUE TITLE
Gemma Approx GELU Issue

### ISSUE THREAD

**Issue by HeegyuKim** [Beomi/Gemma-EasyLM#1]
준범님 안녕하세요 좋은 모델 공유 감사합니다. 공유해주신 2B, 7B 모델을 파인튜닝해서 써보려고 했는데요...!
EasyDeL 이라는 라이브러리 써서 파인튜닝 중인데 GeLU 관련 이슈가 있어서 남겨봅니다.

기존 transformers의 Gemma 구현체 버전에서 GeLU를 사용했는데, 실제로는 bfloat16 오차로 인해 Approximated GeLU (gelu_pytorch_tanh)를 사용해야 하는 버그가 있었습니다. https://github.com/huggingface/transformers/pull/29402

그런데 이 레포 코드를 보니까 현재 학습 후 공유해주신 모델은 GeLU로 튜닝하신 것 같아요
이 경우 최신 transformers에서 config.json 에 `hidden_activation=gelu` 가 없으면 자동으로 gelu_pytorch_tanh 로 변환되는 것 같습니다 (https://github.com/huggingface/transformers/blob/3b8e2932ce743008f63585aae1e1b8b30dc8b3ac/src/transformers/models/gemma/modeling_gemma.py#L175)
그래서 기존의 공유해주신 두 모델의 config.json에 이 부분이 추가되어야 할 것 같구요 

그리고 continual pretraining 과정에서 GeLU로 했으면 오차로 인해 뭔가 문제가 있을수도 있지 않나 싶습니다...

**Comment by Beomi** [comment]
안녕하세요.

https://flax.readthedocs.io/en/latest/api_reference/flax.linen/activation_functions.html#flax.linen.activation.gelu

현재 레포는 pytorch가 아닌 Jax/Flax 구현체이며,
해당 이슈들은 Pytorch구현체쪽에만 있는 이슈입니다.

Act func의 approx는 위 링크에서 확인할 수 있듯 flax의 경우 이미 기본 gelu는 approx=True옵션이 기본입니다 :)

따라서 continual pretrain에서 문제는 없었을 것으로 보이고요,
일반 HF+PyTorch 사용자분들을 위한 config 수정은 해당 항목을 지우는 방향으로 수정해봐야겠네요.
(만약 pytorch로 수정할 경우 flax등에서 로딩에러가 날 것 같습니다.)

**Comment by HeegyuKim** [comment]
아아 그렇군요 ! 늦은 시간에 답변 감사합니다!
